# Generated by Django 2.0.3 on 2018-05-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coin_name', models.CharField(max_length=40)),
                ('Symbol', models.CharField(max_length=10)),
                ('Forked_from', models.CharField(max_length=30)),
                ('Minable', models.CharField(max_length=5)),
                ('Type', models.CharField(max_length=30)),
                ('Token_type', models.CharField(max_length=20)),
                ('ICO', models.CharField(max_length=10)),
                ('Hashing_algorithm', models.CharField(max_length=30)),
                ('Consensus_algorithm', models.CharField(max_length=50)),
                ('Whitepaper', models.CharField(max_length=1000)),
                ('Block_time', models.CharField(max_length=50)),
                ('Founder', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
            ],
        ),
    ]
