# Generated by Django 2.0.3 on 2018-05-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='MarketCap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coins',
            name='Volume_24',
            field=models.IntegerField(default=0),
        ),
    ]
